In [1]:
import numpy as np

In [10]:
a = np.random.rand(5,3)

In [11]:
a

array([[0.07649249, 0.50062272, 0.36112631],
       [0.83795253, 0.421844  , 0.41645871],
       [0.98960919, 0.62696493, 0.40355706],
       [0.62068164, 0.81051056, 0.06362601],
       [0.98105151, 0.97455201, 0.07644008]])

In [14]:
np.argmax(a, axis = 1)

array([1, 0, 0, 1, 0])

In [15]:
np.max(a, axis = 1)

array([0.50062272, 0.83795253, 0.98960919, 0.81051056, 0.98105151])

AttributeError: 'ndenumerate' object has no attribute 'keys'